### ISSUE TITLE
add exclude list?

### ISSUE THREAD

**Issue by systematical** [suterma/globaldarkmode#2]
It works fine for a lot of random sites, but it has problems with anything that has video (youtube, disney plus, etc). Also it doens't work well for sites with an actual dark theme.

Is there a way to edit in a list of exclusions based on url or something?

**Comment by suterma** [comment]
Hi @systematical and thanks for the question. Itself, it has no allow/block feature.

However, with Stylus, the recommended extension to use this global dark theme with, has exactly this feature.  

Open the menu, select the three dots, then select how to exclude a domain/URL:

![grafik](https://github.com/suterma/globaldarkmode/assets/11473920/5b806f6d-72ad-4d90-8881-7c1541249e0b)
